language: node_js
cache:
  directories:
  - node_modules

matrix:
  fast_finish: true
  include:
  - os: osx
    node_js: v6
    sudo: required
    env: BROWSER=Safari
  - os: linux
    node_js: v6
    sudo: false
    env: BROWSER=Firefox
    addons:
      firefox: latest
  - os: linux
    node_js: v6
    sudo: required
    env: BROWSER=Chrome
    addons:
      chrome: stable
    before_script:
      - "sudo chown root /opt/google/chrome/chrome-sandbox"
      - "sudo chmod 4755 /opt/google/chrome/chrome-sandbox"

before_install:
- npm cache clean

script:
- npm run test-node
- npm run test-browsers -- --browsers="$BROWSER"

deploy:
  provider: npm
  email: irfs@bbc.co.uk
  skip_cleanup: true
  api_key:
    secure: cSuf3iiNYM2jSjrk7xNxVLuZn+7S78jktze5MyFdK0rchgOessLY0yIDF9MZbhVbCXGgVbygp+dP5IMHPIDFCqC77WyaWCKdRfretb//RoiRAkEL9B6j8kJ//Sl7LPZ5yYpzotC2tF8zDrw0cucz1sXDTRN9x0C1do2O83hS/qk=
  on:
    tags: true
    repo: bbc/waveform-data.js
